### ISSUE TITLE
Collective addresses: Only recent or way to get earlier ones?

### ISSUE THREAD

**Issue by moll** [riigikogu-kantselei/api#10]
Hey,

I'm happy to see that at least all of the recent public initiatives [Rahvaalgatus](https://rahvaalgatus.ee) sent are returned in https://aavik.riigikogu.ee/api/ems/v1/collective-addresses. What about older ones from 2017? As we're still missing documentation (https://github.com/riigikogu-kantselei/api/issues/8), it's a little unclear whether that's by design or if there's a query parameter to get older initiatives.

Thanks in advance!

**Comment by janesmae** [comment]
Hi, it seems the API demo has no such thing as "collective-addresses" before 2017 (It might have a different document type). The API demo updated reference can be found at: https://aavik.riigikogu.ee/

**Comment by moll** [comment]
We could generalize this issue and ask --- how many collective addresses are returned from the endpoint and if and how should we specify date-time ranges?

**Comment by janesmae** [comment]
> @janesmae: We could generalize this issue and ask --- how many collective addresses are returned from the endpoint and if and how should we specify date-time ranges?

At this point, if the documentation does not state limitations, then there are no limitations. There might be more of an issue with missing data (or different data type).

**Comment by moll** [comment]
I believe this issue was about missing data. :) So, what about collective addresses from 2017?

**Comment by janesmae** [comment]
Currently not available via the API demo or in machine readable formats.
