### ISSUE TITLE
Downloading public files responds with 403 Forbidden

### ISSUE THREAD

**Issue by moll** [riigikogu-kantselei/api#13]
Hey,

I followed the links from a collective-address to a public file referenced in it. I am able to get the file's metadata, but not its contents. For example https://aavik.riigikogu.ee/api/files/882e0370-4730-426f-bf6a-2b4033ece138 responds fine, but https://aavik.riigikogu.ee/api/files/882e0370-4730-426f-bf6a-2b4033ece138/download doesn't. In fact, it seems no matter the UUID, the `/download` URL is off limits.

Followed the docs in https://aavik.riigikogu.ee/swagger-ui.html#/Failid/downloadFileUsingGET.

**Comment by janesmae** [comment]
Hello. This feature is currently not being implemented for the public API demo service. Only metadata is being provided via the Public API demo.

**Comment by janesmae** [comment]
The current API demo uses a different database (not live data, up to a month old). It has to be updated regularly. The API will go live soonish (exact date and time is still unclear at this moment as it's functionality and backend logic is being tested constantly and we still have some issues to solve in those areas).

**Comment by infokujur** [comment]
@janesmae - kas oleks võimalik seda koopiat kuidagi kiiremini tekitada? Meil on ca 3000 inimest e-kirja listis, kes on tellinud endale teavitused. Nad ei soovi tn endale kuu aja vanust teadet.

**Comment by infokujur** [comment]
@janesmae - Kas nüüd on selle staatus muutunud? https://github.com/okestonia/opendata-issue-tracker/issues/60#issuecomment-462297845_

**Comment by janesmae** [comment]
> @janesmae - Kas nüüd on selle staatus muutunud? [okestonia/opendata-issue-tracker#60 (comment)](https://github.com/okestonia/opendata-issue-tracker/issues/60#issuecomment-462297845)_ Hea oleks dokumentatsiooni täiendada, kui see nii ei ole. Mis on lives ja mis on viitega jne

Toodangu API asub api.riigikogu.ee vastavalt infole Avaandmete portaalis.

- https://opendata.riik.ee/andmehulgad/Riigikogu-veebi-avaandmed/ 
- https://www.riigikogu.ee/avaandmed

Käesolev repo sai ka uuenduse vastava infoga.

**Comment by moll** [comment]
Is it me or is the download link still broken?

https://api.riigikogu.ee/api/files/882e0370-4730-426f-bf6a-2b4033ece138/download still reports:

```
HTTP/1.1 403 Forbidden
Connection: keep-alive
Content-Length: 169
Content-Type: text/html
Date: Mon, 11 Feb 2019 12:58:37 GMT
Server: nginx/1.14.2
```

**Comment by marmoluik** [comment]
Downloading files via API is not implemented at the moment.

**Comment by moll** [comment]
Perhaps remove mentions of downloading from the documentation and any links to `/download` from responses until it's implemented.

Do you know when will it be implemented? From the closed issue and "won't fix" tag I'm guessing never? Why not? What use are references to files without an API to obtain them?

**Comment by moll** [comment]
^ Has this been reconsidered since February?
