### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by ottomattas** [riigikogu-kantselei/api#2]
There needs to be a current, usable and attractive documentation!

At the moment, we have a plan where documentation will be a mix of automatic and handwritten text (probably) using the following for tools:
- [Swagger](http://swagger.io/)
- [Spring REST Docs](https://projects.spring.io/spring-restdocs/)

We have taken [Spotify's WEB-API](https://developer.spotify.com/web-api/endpoint-reference/) as an example for us.

**Comment by ottomattas** [comment]
Initial discussion in okestonia/opendata-issue-tracker#60

**Comment by moll** [comment]
I noticed there's something generated by Swagger at https://aavik.riigikogu.ee/swagger-ui.html, but it too doesn't include collective-addresses. Is it fresh? Is it supposed to be the canonical documentation?

**Comment by janesmae** [comment]
The current documentation is provided via the link on the website: https://aavik.riigikogu.ee/
Collective-addresses section can be found under "documents".
