### ISSUE TITLE
Mainida README-s GitHubi töökeeleks eesti keel

### ISSUE THREAD

**Issue by moll** [riigikogu-kantselei/api#21]
Hei

Kuna Janek palus GitHubis suhelda eesti keeles, siis vast tasuks see ka README-s ära mainida. Olin seni arusaamal, et siinne töökeel on inglise keel, kuna README ja juhendid on inglise keeles.

Janek:
> Andri, palve oleks et teemad võiks olla GitHubis eesti keeles, kuna see on ikkagi riigikeel.

**Comment by janesmae** [comment]
done
README uuendatud koos vastava alamlõiguga.

**Comment by moll** [comment]
Tänu!

**Comment by janesmae** [comment]
ptv!
