### ISSUE TITLE
Dates and times should be in ISO 8601 format

### ISSUE THREAD

**Issue by moll** [riigikogu-kantselei/api#3]
Lo!

Times and dates returned by the API in various responses are currently in a proprietary format: some in milliseconds from possibly Unix epoch (with no clarity how leap seconds and other time peculiarities are handled) and some in the `DD.MM.YYYY` format.

I propose they all be replaced with extended ISO 8601 formats, which look like the following:
```
2015-06-18
2015-06-18T13:37:42Z
2015-06-18T13:37:42+02:00
```

The last for times where the local time is also important. The last SHOULD include a IANA time zone in a separate property if needed. If not, the first two — dates and UTC times — suffice.

**Comment by moll** [comment]
For the record, the IANA time zone for Estonia is "Europe/Tallinn".

**Comment by janesmae** [comment]
This should be resolved in the new API demo.
