### ISSUE TITLE
Need to specify license

### ISSUE THREAD

**Issue by boamaod** [riigikogu-kantselei/api#6]
For use in portals paying attention to copyright like Wikipedia etc, license or not requiring license needs to be specified. If the data is in public domain, [official guide](https://www.ria.ee/public/Arhitektuur/Avaandmete_loomise_juhend.pdf) suggests using CC0 for clarity and usability in all jurisdictions.

**Comment by janesmae** [comment]
Hi, Thanks for the proposal. It has been forwarded to the task group dealing with the API demo. Currently, the API is provided as a demo and data as-is. It is definitely not live. If at some point the API goes completely live, the issue with licensing will be resolved.
