### ISSUE TITLE
Collective addresses: API Documentation

### ISSUE THREAD

**Issue by tiblu** [riigikogu-kantselei/api#8]
Some documentation notes/suggestions specific to Collective Addresses API (https://aavik.riigikogu.ee/api/ems/v1/collective-addresses).

* Public documentation - but as I understand that depends on - https://github.com/riigikogu-kantselei/api/issues/2
* ``status.statusCode`` - List all possible values.
* ``relatedVolumes`` - Any examples of these? What data would it contain and how would it be of interest the people?

**Comment by moll** [comment]
I don't see any collective-address docs in the [new?] Swagger generated docs either: https://aavik.riigikogu.ee/swagger-ui.html.

**Comment by janesmae** [comment]
Hi. The v1 API demo is deprecated. Please refer to https://aavik.riigikogu.ee/ for a v2 (updated) API demo reference. The collective-address section is located under documents. Enjoy.

**Comment by moll** [comment]
@janesmae: I remember there being some query parameters to filter outputs. I don't see any in the v2 docs...

**Comment by janesmae** [comment]
All the available parameters should be documented in the reference docs. No additional (and undocumented) filters used.
