### ISSUE TITLE
Add state of API to readme

### ISSUE THREAD

**Issue by eyeinsky** [riigikogu-kantselei/api#9]
Would be great to have info on what's the current state of the API right on top of the readme! 

Currently I simply get a 404 when I click the [link](https://aavik.riigikogu.ee/api/ems/v1/raml/ems-api-v1.html) --  with no hint of is the API in some queryable state (i.e by calling it by having accept json), or is it just a stub that only returns 404s.

Thanks!

**Comment by janesmae** [comment]
Hello.

We have internally re-classified this project more as a demo of the API, not ready for production use. In the future, please visit https://aavik.riigikogu.ee/ to get access to the latest version of the API demo documentation.
